<?php

declare(strict_types=1);

namespace Contenir\Sitemap\Mezzio\Source;

use Contenir\Sitemap\Mezzio\SitemapEntry;
use Contenir\Sitemap\Mezzio\SitemapSourceInterface;
use Contenir\Workflow\Strategy\ResourceStrategyInterface;
use Laminas\Cache\Exception\ExceptionInterface as CacheException;
use Mezzio\Router\Exception\RuntimeException as RouterException;
use Mezzio\Router\RouterInterface;
use Override;
use Psr\Container\ContainerExceptionInterface;

use function array_key_exists;
use function is_array;
use function is_string;

/**
 * The sitemap entries of a contenir-workflow-mezzio navigation: one per
 * visible page that has a registered route, in navigation order, with the
 * URL generated by the Mezzio router.
 *
 * As laminas-view's sitemap helper does with a laminas-navigation
 * container, an invisible page hides its whole branch, and a lastmod,
 * changefreq or priority the sitemap protocol does not accept is left out
 * rather than failing the sitemap. Pages without a route of their own (a
 * folder resource without middleware) are skipped, their children are not.
 *
 * @api
 */
final readonly class WorkflowNavigationSource implements SitemapSourceInterface
{
    public function __construct(
        private ResourceStrategyInterface $strategy,
        private RouterInterface $router,
    ) {}

    /**
     * @return list<SitemapEntry>
     *
     * @throws CacheException
     * @throws ContainerExceptionInterface When a workflow cannot be created.
     * @throws RouterException When a page's route needs parameters to generate its URL.
     */
    #[Override]
    public function getEntries(): array
    {
        return $this->entries($this->strategy->getNavigationConfig(), $this->strategy->getRouteConfig());
    }

    /**
     * @param array<array-key, mixed> $pages
     * @param array<string, mixed> $routes
     * @param list<SitemapEntry> $entries
     *
     * @return list<SitemapEntry>
     *
     * @throws RouterException When a page's route needs parameters to generate its URL.
     *
     * @mago-expect analysis:mixed-assignment Navigation pages are untyped arrays; each value is checked here.
     */
    private function entries(array $pages, array $routes, array $entries = []): array
    {
        foreach ($pages as $page) {
            if (! is_array($page) || false === ($page['visible'] ?? true)) {
                continue;
            }

            $route = $page['route'] ?? null;
            if (is_string($route) && array_key_exists($route, $routes)) {
                $entries[] = new SitemapEntry(
                    location: $this->router->generateUri($route),
                    lastModified: PageValue::lastModified($page['lastmod'] ?? null),
                    changeFrequency: PageValue::changeFrequency($page['changefreq'] ?? null),
                    priority: PageValue::priority($page['priority'] ?? null),
                );
            }

            $children = $page['pages'] ?? null;
            if (is_array($children)) {
                $entries = $this->entries($children, $routes, $entries);
            }
        }

        return $entries;
    }
}
